config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"

  get "home/about", to: "homes#about", as: "about"

  resources :users, only: [:index, :show, :edit, :update]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  # ===== Validation =====
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :database_authenticatable（パスワードの正確性を検証）
  # :registerable（ユーザ登録や編集、削除）
  # :recoverable（パスワードをリセット）
  # :rememberable（ログイン情報を保存）
  # :validatable（email のフォーマットなどのバリデーション）
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :ensure_owner!, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
    @book = Book.new
    @sidebar_user = current_user
  end

  def show
    @sidebar_user = current_user
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to @book, notice: "Book was successfully created."
    else
      @books = Book.includes(:user).order(created_at: :desc)
      @sidebar_user = current_user
      flash.now[:alert] = "error: Could not create book."
      render :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully updated."
    else
      flash.now[:alert] = "error: Could not update book."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def ensure_owner!
    return if @book.user == current_user
    redirect_to books_path, alert: "error: You can edit only your own book."
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if user_signed_in?
      @sidebar_user = current_user
      @book         = Book.new
      @books        = current_user.books.includes(:user).order(created_at: :desc)
    end
  end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
  before_action :ensure_myself!, only: [:edit, :update]

  def index
    @sidebar_user = current_user
    @book = Book.new
    @users = User.order(:id)
  end

  def info
    @user = current_user
    @books = @user.books.order(created_at: :desc)
    @sidebar_user = @user
    @book = Book.new
    render "books/index"
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(created_at: :desc)
    @sidebar_user = @user
    @book = Book.new

    render "books/index"
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Profile was successfully updated."
    else
      flash.now[:alert] = "error: Could not update profile."
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  # only current user
  def ensure_myself!
    return if @user == current_user
    redirect_to user_path(current_user), alert: "error: You can edit only your own profile."
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="mb-4">Editing Book</h2>

      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group mt-3">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, rows: 5, class: "form-control" %>
        </div>

        <div class="mt-3">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>

      <div class="mt-3">
        <%= link_to "Show", @book %> |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="row">
  <%= render "shared/sidebar", user: @sidebar_user, book: @book %>

  <section class="offset-md-1 col-md-8">
    <h3>Books</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th class="text-right">Title</th>
          <th class="text-right">Opinion</th>
          <th class="text-right"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td style="width:100px">
              <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(100,100), class: "rounded" %>
              <% end %>
            </td>
            <td class="text-right align-middle"><%= link_to book.title, book %></td>
            <td class="text-right align-middle"><%= truncate(book.body, length: 80) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
</div>

app/views/books/show.html.erb
<div class="row">
  <!-- Sidebar -->
  <%= render "shared/sidebar", user: @book.user, book: Book.new %>

  <!-- Book detail -->
  <section class="offset-md-1 col-md-8">
    <h3>Book detail</h3>
    <table class="table">
      <tr>
        <td style="width:120px">
          <%= image_tag @book.user.get_profile_image(100,100), class: "rounded" %>
          <%= link_to @book.user.name, @book.user %>
        </td>
        <td class="text-right align-middle" ><%= link_to @book.title, @book %></td>
        <td class="text-right align-middle" ><%= @book.body %></td>
        <td class="text-right align-middle" >
          <% if @book.user == current_user %>
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
            <%= link_to "Destroy", @book, method: :delete,
                        data: { confirm: "Are you sure?" },
                        class: "btn btn-sm btn-danger" %>
          <% end %>
        </td>
      </tr>
    </table>
  </section>
</div>

app/views/homes/about.html.erb
<h1 class="text-center display-4"> Welcome to <i class="fa-solid fa-book"></i> Bookers!</h1>

app/views/homes/top.html.erb
<div class="jumbotron text-center">
  <h1 class="display-4">Welcome to Bookers !!</h1>
  <p class="lead">In Bookers, you can share and exchange your opinions, inpressions and emotions about various books!</p>

  <div class="mt-4">
    <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-lg btn-block mb-2" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg btn-block" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer text-center py-3 mt-auto">
  <div class="container">
    <small>Copyright © 2025 Yuris Inc. All rights reserved.</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">
    <i class="fa-solid fa-book"></i> Bookers
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user), class: "nav-link text-light" do %>
            <i class="fa-solid fa-home"></i> Home
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: "nav-link text-light" do %>
            <i class="fa-solid fa-users"></i> Users
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to books_path, class: "nav-link text-light" do %>
            <i class="fa-solid fa-book-open"></i> Books
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
            <i class="fa-solid fa-right-from-bracket"></i> Log out
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to root_path, class: "nav-link text-light" do %>
            <i class="fa-solid fa-home"></i> Home
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to about_path, class: "nav-link text-light" do %>
            <i class="fa-solid fa-link"></i> About
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
            <i class="fa-solid fa-user-plus"></i> Sign up
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link text-light" do %>
            <i class="fa-solid fa-right-to-bracket"></i> Log in
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# import font %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Funnel+Sans:wght@400;600&family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/d31d06fbbc.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container mt-3">
      <% if notice %><div class="alert alert-success"><%= notice %></div><% end %>
      <% if alert  %><div class="alert alert-danger"><%= alert  %></div><% end %>
    <%# for sticky footer %>
    <body class="d-flex flex-column min-vh-100">
    <div class="flex-grow-1">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <strong>error:</strong>
    <%= pluralize(resource.errors.count, "error") %> prohibited this record from being saved.
    <ul class="mb-0 mt-2">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="col-md-3">
  <h4 class="mb-3">User info</h4>
  <%= image_tag user.get_profile_image(150,150), class: "img-fluid rounded mb-3" %>

  <div class="d-flex justify-content-between py-1 border-bottom">
    <strong>name</strong>
    <span><%= user.name %></span>
  </div>

  <div class="d-flex justify-content-between py-1 border-bottom">
    <strong>introduction</strong>
    <span><%= user.introduction.presence %></span>
  </div>

  <%= link_to raw('<i class="fa-solid fa-user-gear mr-1"></i>'),
              edit_user_path(user),
              class: "btn btn-outline-secondary w-100 mt-3" %>

  <h4 class="mt-4 mb-3">New book</h4>

  <!-- ✅ error message -->
  <%= render "shared/error_messages", resource: book %>

  <%= form_with model: book, url: books_path, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :body, "Opinion" %>
      <%= f.text_area :body, rows: 4, class: "form-control" %>
    </div>
    <%= f.submit "Create Book", class: "btn btn-success w-100" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= render "shared/error_messages", resource: @user %>

<%= form_with model: @user, local: true do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :profile_image %>
    <%= f.file_field :profile_image %>
  </div>
  <div>
    <%= f.label :introduction %>
    <%= f.text_area :introduction, rows: 3 %>
  </div>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render "shared/sidebar", user: @sidebar_user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h3>Users</h3>
      <table class="table">
        <thead>
          <tr>
            <th style="width:100px; text-align:left;">Image</th>
            <th class="text-center">Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td class="text-center">
                <%= image_tag user.get_profile_image(80,80), class: "rounded" %>
              </td>
              <td class="align-middle text-center">
                <%= user.name %>
              </td>
              <td class="text-right align-middle">
                <%= link_to "Show", user_path(user), class: "btn btn-outline-secondary btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-3 text-center">
    <%= image_tag @user.get_profile_image(200,200), class: "img-fluid rounded mb-2" %>
    <h4><%= @user.name %></h4>
    <p class="text-muted"><%= @user.introduction %></p>
    <% if @user == current_user %>
      <%= link_to "Edit", edit_user_path(@user), class: "btn btn-outline-secondary btn-sm" %>
    <% end %>
  </aside>

  <section class="offset-md-1 col-md-8">
    <h3 class="mb-3">Books</h3>
    <ul class="list-group">
      <% @user.books.each do |b| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= link_to b.title, b %>
          <span class="badge badge-light"><%= b.user.name %></span>
        </li>
      <% end %>
    </ul>
  </section>
</div>